CREATE TABLE user (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    username VARCHAR NOT NULL,
    hashedname VARCHAR NOT NULL
);
CREATE TABLE song (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    title VARCHAR NOT NULL,
    artist VARCHAR NOT NULL,
    link VARCHAR NOT NULL,
    genre VARCHAR NOT NULL,
    comment VARCHAR NOT NULL,
    stamp INTEGER NOT NULL,
    addedby INTEGER NOT NULL,
    FOREIGN KEY(addedby) REFERENCES user(id)
);
CREATE TABLE rating (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    song INTEGER NOT NULL,
    user INTEGER NOT NULL,
    yeahnah INTEGER NOT NULL,
    comment VARCHAR NOT NULL,
    FOREIGN KEY(song) REFERENCES song(id),
    FOREIGN KEY(user) REFERENCES user(id)
);
